### PR TITLE
verify ownership

### PR DESCRIPTION
**Pull request by VictorCuevas98**
Added a ownership file to track activity

### CODE REVIEW

**Comment by VictorCuevas98** [comment]
thats okey

**Comment by VictorCuevas98** [comment]
I hope that everything is okey, looking forward to pull these changes.

**Comment by ZanateDesign** [comment]
I'm checking this out, I'll let you know when I finish.

**Review by ZanateDesign — APPROVED** [review]
Everything seems to be in good conditions.

**Pull request merged**
